# Generated by Django 4.2.9 on 2024-03-03 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieinfo',
            name='summery',
        ),
    ]
