# Generated by Django 5.0.2 on 2024-03-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movieinfo_summery'),
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('year', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='movieInfo',
        ),
    ]
